# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{verity}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Geldart"]
  s.date = %q{2010-10-09}
  s.email = %q{joe@joegeldart.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "AUTHORS",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "lib/verity.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/jgeldart/verity}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.7")
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{verity is a DSL for writing validations for arbitrary objects}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
  s.add_development_dependency(%q<yard>, [">= 0.5.3"])
  s.add_development_dependency(%q<yardstick>, [">= 0.1.0"])
end

